### ISSUE TITLE
XPP3 & javax QName

### ISSUE THREAD

**Issue by aslom** [aslom/xpp3#2]
reported by Arnaud :

My issue is I suspect XPP3 dependency to trigger java runtime checksum warnings, because of javax QName  redefinition

As QName is now standard in Java distributions.

 

xpp3 1.1.4c_min does not includes QName, but in the perspective of upgrading :

 

    Is there a xpp3 1.1.6 ‘MIN’ artefact provided without javax package ?

Else could you provide one ?

 

Note: the QName.java file from the xpp3 sources has the following

comment at the top:

 

/**

* NOTE: copied from Apache AXIS until QName is really standard in some JDK version ...

….

* @version 1.1

*/

 

 

Runtime issues :

javax.xml.namespace.QName :  Invalid CheckSum Class=javax.xml.namespace.QName, ExpectedCheckSum=1c69acf6716870109379596033ebe11a, ActualCheckSum= d225d319c7382d16e70eb79ced85f644

**Comment by aslom** [comment]
Current build of min does nto have QName but full jar has it:

```
$ jar tvf xpp3_min-1.1.5.jar |grep QName

$ jar tvf xpp3-1.1.5.jar |grep QName
  2748 Wed Apr 06 00:03:38 EDT 2016 javax/xml/namespace/QName.class
```

**Comment by arnaud-penet** [comment]
Hi & thx for your help !

Arnaud

**Comment by arnaud-penet** [comment]
Hi, 

Do you know when a new release is planned with the fix ?

Thank you

Arnaud

**Comment by aslom** [comment]
Opened issue #3 to track it

**Comment by arnaud-penet** [comment]
Hi, 

Any news on the release ?

Thx
Arnaud
